package com.p2plending.application.lender.usecase;

import com.p2plending.application.lender.dto.RegisterLenderCommand;
import com.p2plending.application.lender.dto.LenderDTO;
import com.p2plending.domain.lender.entity.Lender;
import com.p2plending.domain.borrower.entity.KTP;
import com.p2plending.domain.lender.repository.LenderRepository;
import com.p2plending.domain.shared.Money;

public class RegisterLenderUseCaseImpl implements RegisterLenderUseCase {
    private final LenderRepository lenderRepository;

    public RegisterLenderUseCaseImpl(LenderRepository lenderRepository) {
        this.lenderRepository = lenderRepository;
    }

    @Override
    public LenderDTO execute(RegisterLenderCommand command) {
        // Create value objects
        KTP ktp = new KTP(command.getNama(), command.getKtpNumber());
        Money saldo = new Money(command.getInitialBalance(), "IDR");

        // Create Lender entity
        Lender lender = new Lender(
            null, // ID will be generated by repository
            command.getNama(),
            command.getNoTelepon(),
            command.getAlamat(),
            ktp,
            command.getPekerjaan(),
            saldo
        );

        // Save lender
        Lender savedLender = lenderRepository.save(lender);

        // Return DTO
        return new LenderDTO(
            savedLender.getId(),
            savedLender.getNama(),
            savedLender.getKtp().getNomorKtp(),
            savedLender.getSaldo().getAmount()
        );
    }
}