package com.p2plending.application.borrower.usecase;

import com.p2plending.application.borrower.dto.BorrowerDTO;
import com.p2plending.application.borrower.dto.RegisterBorrowerCommand;
import com.p2plending.domain.borrower.repository.BorrowerRepository;
import com.p2plending.domain.borrower.entity.Borrower;
import com.p2plending.domain.borrower.entity.KTP;
import com.p2plending.domain.shared.Money;
import java.math.BigDecimal;

public class RegisterBorrowerUseCase {
    private final BorrowerRepository borrowerRepository;

    public RegisterBorrowerUseCase(BorrowerRepository borrowerRepository) {
        this.borrowerRepository = borrowerRepository;
    }

    public BorrowerDTO execute(RegisterBorrowerCommand command) {
       KTP ktp = new KTP(command.getName(), command.getKtpNumber());
       Money gaji = new Money(BigDecimal.valueOf(command.getMonthlySalary()), "IDR");

        Borrower borrower = new Borrower(
                null, // ID will be generated by the repository
                command.getName(),
                command.getNoTelepon(),
                command.getAlamat(),
                ktp,
                gaji,
                "Pegawai", // Placeholder for pekerjaan
                command.getCreditScore()
        );

        Borrower savedBorrower = borrowerRepository.save(borrower);

        return new BorrowerDTO(
                savedBorrower.getId(),
                savedBorrower.getNama(),
                savedBorrower.getKtp().getNomorKtp(),
                savedBorrower.getGaji().getAmount(),
                savedBorrower.getCreditScore()
        );
    }
}